### ISSUE TITLE
IndexError when c is 1, 2 or 3

### ISSUE THREAD

**Issue by aaossa** [genisott/pycondor#1]
Hi, I've been using this BRIM implementation for a few days, but I can't get it to work with `c` equal to 1, 2 or 3. I know that it might not be useful for `c=1`, but I don't get why it does not work for 2 or 3. Instead, I just see an index error (this is for `c=3`). 

```
Object creation:
  Elapsed time: 0.00 sec.
Initial community structure without projection:
Initial modularity:  0.46173469387755106
  Elapsed time: 0.00 sec.
Matrix computation:
  Elapsed time: 0.00 sec.
Traceback (most recent call last):
  File "...\demo.py", line 11, in <module>
    co.brim(c=3)
  File "...\pycondor\condor\condor.py", line 286, in brim
    B,m,T0,R0,gn,rg = self.matrices(c)
  File "...\pycondor\condor\condor.py", line 247, in matrices
    T0[edge]=1
IndexError: index 3 is out of bounds for axis 1 with size 3
```

Script used:

```python
import condor
import pandas as pd


df = pd.read_csv("edgelist.txt", sep=" ", index_col=0, header=0)
co = condor.condor_object(dataframe=df)
co.initial_community()
co.brim(c=3)
```

Contents of "edgelist.txt":

```
 from to weight
1 A B 1
2 A D 1
3 A E 1
4 A G 1
5 A H 1
6 B C 1
7 B E 1
8 C I 1
9 C K 1
10 C L 1
11 D A 1
12 D C 1
13 D H 1
14 D I 1

```

**Comment by MustakimBillah** [comment]
@aaossa , hey were you able to run the program?
